services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: depi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d depi"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./server
    environment:
      # inside the compose network, the host is `db`
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/depi
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      # live-reload in dev
      - ./server:/app
