"""add user

Revision ID: 962b6c933db8
Revises: 3150db528604
Create Date: 2025-08-28 19:18:29.442583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962b6c933db8'
down_revision = '3150db528604'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
