"""sync user schema

Revision ID: b0a34e1ed88a
Revises: 72a762e6b434
Create Date: 2025-08-28 19:41:58.633310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a34e1ed88a'
down_revision = '72a762e6b434'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
